from pathlib import Path

p=Path('public/account.html')
s=p.read_text(encoding='utf-8')
mark='account-order-flow-v1'
if mark in s:
    print('already patched'); raise SystemExit(0)

css='''\n/* account-order-flow-v1 */\n.order-step{margin:10px 0;padding:10px 12px;border-radius:11px;background:#eef4fb;border:1px solid #cbd9ea;font-weight:900;color:#15395f}.order-step.wait{background:#fff5d8;border-color:#e6c46e;color:#7b570e}.order-step.ok{background:#e5f5e9;border-color:#9fd0aa;color:#17633c}.order-step.done{background:#edf0f4;border-color:#cfd6df;color:#566170}.order-next{display:inline-flex;align-items:center;gap:6px;margin-top:8px;padding:9px 11px;border-radius:9px;background:#c9861b;color:#fff;font-weight:900}.order-flow-note{font-size:.83rem;color:#687386;margin-top:6px}.mini-order.current-action{border-width:2px;border-color:#c9861b;box-shadow:0 6px 18px #c9861b20}\n'''
s=s.replace('</style>',css+'</style>',1)

needle="    const card=x=>`<div class=\"mini-order ${x.archived?'archived':''}\"><b>${esc(x.itemTitle)}</b><div>رقم الطلب: ${esc(x.orderNumber||'—')}</div><div>الإجمالي النهائي: ${accountMoney(x.buyerTotal)}</div><div>الشحن: ${x.shippingFeeConfirmed?accountMoney(x.shippingFee):'بانتظار التحديد'}</div><div class=\"status\">${esc(x.statusLabel||x.status)}${x.archived?' · محفوظ بالسجل':''}</div><div>${esc(paymentStatusText(x))}</div>${x.paymentProofStatus==='rejected'?`<div class=\"payment-rejected\">سبب الرفض: ${esc(x.paymentProofRejectNote||'تعذر التحقق من الإثبات')} — يمكنك رفع إثبات جديد.</div>`:''}${x.paymentReference?`<div>مرجع التحويل: ${esc(x.paymentReference)}</div>`:''}${x.shippingCompany?`<div>شركة الشحن: ${esc(x.shippingCompany)}</div>`:''}${x.trackingNumber?`<div>التتبع: ${esc(x.trackingNumber)}</div>`:''}<div class=\"mini-order-actions\"><button onclick=\"openInvoice('${esc(x.id)}')\">🧾 عرض الفاتورة</button>${actions(x)}</div></div>`;"
if needle not in s:
    raise RuntimeError('card template not found')
helper='''    // account-order-flow-v1: one visible next step per order.\n    const orderNextStep=x=>{\n      const paid=x.paymentStatus==='paid';\n      const proof=x.paymentStatus==='proof_submitted';\n      const shipped=['shipped','delivered','completed'].includes(x.status);\n      const delivered=['delivered','completed'].includes(x.status);\n      const hasAddress=!!(x.shippingAddress&&(x.shippingAddress.recipientName||x.shippingAddress.addressLine||x.shippingAddress.city));\n      if(x.archived)return {cls:'done',text:'الطلب محفوظ في السجل',action:''};\n      if(delivered)return {cls:'done',text:x.status==='completed'?'الطلب مكتمل':'تم الاستلام',action:''};\n      if(shipped)return {cls:'ok',text:'تم الشحن'+(x.trackingNumber?' — تابع الشحنة':' — بانتظار رقم التتبع'),action:''};\n      if(paid)return {cls:'ok',text:x.status==='ready_to_ship'?'جاهز للشحن':'تم السداد — الطلب قيد التجهيز',action:''};\n      if(proof)return {cls:'wait',text:'تم إرسال إثبات السداد — بانتظار اعتماد الإدارة',action:''};\n      if(!hasAddress)return {cls:'wait',text:'الخطوة التالية: أكمل عنوان الشحن',action:'address'};\n      if(!x.shippingFeeConfirmed)return {cls:'wait',text:'العنوان محفوظ — بانتظار تحديد تكلفة الشحن من الإدارة',action:''};\n      return {cls:'wait',text:'الطلب جاهز للسداد الآن',action:'pay'};\n    };\n    const orderActionHint=x=>{const n=orderNextStep(x);if(n.action==='address')return `<button class=\"order-next\" onclick=\"document.getElementById('shippingPanel')?.scrollIntoView({behavior:'smooth'})\">📦 أكمل عنوان الشحن</button>`;if(n.action==='pay')return `<span class=\"order-next\">💳 جاهز للسداد</span>`;return ''};\n'''
newcard="    const card=x=>{const step=orderNextStep(x);return `<div class=\"mini-order ${x.archived?'archived':''} ${step.action?'current-action':''}\"><b>${esc(x.itemTitle)}</b><div>رقم الطلب: ${esc(x.orderNumber||'—')}</div><div>الإجمالي النهائي: ${accountMoney(x.buyerTotal)}</div><div>الشحن: ${x.shippingFeeConfirmed?accountMoney(x.shippingFee):'بانتظار التحديد'}</div><div class=\"order-step ${step.cls}\">${esc(step.text)}</div><div class=\"order-flow-note\">${x.shippingFeeConfirmed?'قيمة الشحن معتمدة ضمن الإجمالي النهائي':'لن يتفعّل السداد قبل اعتماد تكلفة الشحن'}</div><div class=\"status\">${esc(x.statusLabel||x.status)}${x.archived?' · محفوظ بالسجل':''}</div><div>${esc(paymentStatusText(x))}</div>${x.paymentProofStatus==='rejected'?`<div class=\"payment-rejected\">سبب الرفض: ${esc(x.paymentProofRejectNote||'تعذر التحقق من الإثبات')} — يمكنك رفع إثبات جديد.</div>`:''}${x.paymentReference?`<div>مرجع التحويل: ${esc(x.paymentReference)}</div>`:''}${x.shippingCompany?`<div>شركة الشحن: ${esc(x.shippingCompany)}</div>`:''}${x.trackingNumber?`<div>التتبع: ${esc(x.trackingNumber)}</div>`:''}${orderActionHint(x)}<div class=\"mini-order-actions\"><button onclick=\"openInvoice('${esc(x.id)}')\">🧾 عرض الفاتورة</button>${actions(x)}</div></div>`};"
s=s.replace(needle,helper+newcard,1)

# Explain sections as views of the same order lifecycle, not separate workflows.
s=s.replace('<h2>مشترياتي وطلباتي</h2>','<h2>مشترياتي وطلباتي</h2>',1)
s=s.replace('<h2>💳 المستحقات</h2>','<h2>💳 المستحقات</h2>',1)
s=s.replace('السداد الجماعي يتفعّل فقط عندما تصبح جميع الطلبات غير المسددة جاهزة للسداد ويكون مبلغ الشحن معتمدًا لكل طلب. ويمكن سداد أي طلب جاهز منفردًا من بطاقته.','المستحقات هنا هي نفس الطلبات التي أصبحت جاهزة للسداد بعد حفظ العنوان واعتماد تكلفة الشحن. لا يتم إنشاء طلب أو فاتورة جديدة.',1)
s=s.replace('احفظ عنوان التسليم هنا. ينسخ النظام العنوان تلقائيًا إلى الطلبات النشطة التي لم تُشحن بعد، بينما تبقى الطلبات المشحونة محفوظة بعنوانها السابق.','احفظ عنوان التسليم هنا مرة واحدة. يرتبط بنفس الطلب، ثم تنتظر اعتماد تكلفة الشحن، وبعدها ينتقل الطلب نفسه إلى مرحلة السداد ثم التجهيز والشحن.',1)

# cache bust
s=s.replace('/visitor.css?v=5.6.2-r9.5','/visitor.css?v=5.6.2-r9.5-orderflow1',1)
p.write_text(s,encoding='utf-8')
print('patched account order flow')
