from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
server=ROOT/'server.py'
account=ROOT/'public'/'account.html'

# --- server: if an active order still carries an old/empty address, refresh it from the customer profile before blocking shipment.
s=server.read_text(encoding='utf-8')
marker='# shipping-address-activation-v1'
if marker not in s:
    old="""                if status in ('ready_to_ship','shipped'):\n                    addr=row.get('shippingAddress') if isinstance(row.get('shippingAddress'),dict) else {}\n                    if not str(addr.get('country') or '').strip() or not str(addr.get('city') or '').strip() or not str(addr.get('addressLine') or '').strip():\n                        self.sendj({'error':'أكمل عنوان التسليم في حساب العميل قبل جعل الطلب جاهزًا للشحن'},409); return\n                    if not str(row.get('shippingCompany') or '').strip():\n"""
    new="""                if status in ('ready_to_ship','shipped'):\n                    # shipping-address-activation-v1\n                    addr=row.get('shippingAddress') if isinstance(row.get('shippingAddress'),dict) else {}\n                    def _shipping_complete(a):\n                        return bool(str((a or {}).get('country') or '').strip() and str((a or {}).get('city') or '').strip() and str((a or {}).get('addressLine') or '').strip())\n                    # Old orders may still have an empty address even after the customer saved a complete profile address.\n                    # Before rejecting the admin action, pull the latest saved customer address into this order.\n                    if not _shipping_complete(addr):\n                        pid=str(row.get('participantId') or '')\n                        person=next((x for x in load_people() if str(x.get('id') or '')==pid),None)\n                        profile_addr=(person or {}).get('shippingAddress') if isinstance((person or {}).get('shippingAddress'),dict) else {}\n                        if _shipping_complete(profile_addr):\n                            row['shippingAddress']=dict(profile_addr)\n                            row['shippingAddressSyncedAt']=datetime.datetime.now().isoformat()\n                            row['updated']=datetime.datetime.now().isoformat()\n                            save_json(ORDERS,{'orders':orders})\n                            addr=row['shippingAddress']\n                    if not _shipping_complete(addr):\n                        missing=[]\n                        if not str(addr.get('country') or '').strip(): missing.append('الدولة')\n                        if not str(addr.get('city') or '').strip(): missing.append('المدينة')\n                        if not str(addr.get('addressLine') or '').strip(): missing.append('العنوان بالتفصيل')\n                        self.sendj({'error':'عنوان التسليم غير مكتمل. أكمل '+('، '.join(missing) if missing else 'بيانات العنوان')+' في حساب العميل أولًا','code':'shipping_address_incomplete','actionUrl':'/account?focus=shipping#shippingPanel','missingAddressFields':missing},409); return\n                    if not str(row.get('shippingCompany') or '').strip():\n"""
    if old not in s:
        raise RuntimeError('ready_to_ship address validation block not found')
    s=s.replace(old,new,1)
    server.write_text(s,encoding='utf-8')

# --- account: direct customer routing to the address form, validation, and activation message.
a=account.read_text(encoding='utf-8')
if 'shipping-address-focus-v1' not in a:
    # Add a highlighted target state for the address panel.
    a=a.replace('</style>','''\n/* shipping-address-focus-v1 */\n#shippingPanel.address-required{border:2px solid #c9861b;box-shadow:0 0 0 4px #c9861b22,0 12px 30px #071b3518}\n#shippingPanel.address-required .address-form{background:#fff8e8;border:1px solid #e7c675;border-radius:14px;padding:12px}\n#addressMsg.address-ok{display:inline-block;margin-top:8px;color:#17633c;font-weight:900}\n</style>''',1)

    # Replace the old scroll-only helper with a direct focus helper.
    old_hint="""    const orderActionHint=x=>{const n=orderNextStep(x);if(n.action==='address')return `<button class=\"order-next\" onclick=\"document.getElementById('shippingPanel')?.scrollIntoView({behavior:'smooth'})\">📦 أكمل عنوان الشحن</button>`;if(n.action==='pay')return `<span class=\"order-next\">💳 جاهز للسداد</span>`;return ''};\n"""
    new_hint="""    // shipping-address-focus-v1\n    const focusShippingAddress=(force=false)=>{\n      const panel=document.getElementById('shippingPanel'); if(!panel)return;\n      panel.classList.add('address-required');\n      panel.scrollIntoView({behavior:'smooth',block:'start'});\n      setTimeout(()=>{\n        const ids=['addrName','addrPhone','addrCountry','addrCity','addrLine'];\n        const first=ids.map(id=>document.getElementById(id)).find(el=>el && !String(el.value||'').trim());\n        (first||document.getElementById('addrName'))?.focus?.();\n      },350);\n      if(force){try{history.replaceState(null,'',location.pathname+'?focus=shipping#shippingPanel')}catch(_){}}\n    };\n    window.focusShippingAddress=focusShippingAddress;\n    const orderActionHint=x=>{const n=orderNextStep(x);if(n.action==='address')return `<button class=\"order-next\" onclick=\"focusShippingAddress(true)\">📦 أكمل عنوان الشحن الآن</button>`;if(n.action==='pay')return `<span class=\"order-next\">💳 جاهز للسداد</span>`;return ''};\n"""
    if old_hint not in a:
        raise RuntimeError('order address hint block not found')
    a=a.replace(old_hint,new_hint,1)

    # After orders load, if the customer reached the account specifically for the address, jump straight there.
    old_rows="""    let rows=d.requests||[];accountOrdersCache=rows;"""
    new_rows="""    let rows=d.requests||[];accountOrdersCache=rows;\n    const wantsAddress=(new URLSearchParams(location.search)).get('focus')==='shipping'||location.hash==='#shippingPanel';\n    const activeNeedsAddress=rows.some(x=>!x.archived&&!['shipped','delivered','completed','cancelled','returned'].includes(String(x.status||''))&&!(x.shippingAddress&&String(x.shippingAddress.country||'').trim()&&String(x.shippingAddress.city||'').trim()&&String(x.shippingAddress.addressLine||'').trim()));\n    if(wantsAddress||activeNeedsAddress)setTimeout(()=>window.focusShippingAddress?.(false),120);"""
    if old_rows not in a:
        raise RuntimeError('loadOrders rows marker not found')
    a=a.replace(old_rows,new_rows,1)

    # Stronger save validation and clear activation state after a successful save.
    old_save="""if($('saveAddress'))$('saveAddress').onclick=async()=>{let v=NawaderVisitor.get();if(!v)return;let shippingAddress={recipientName:$('addrName').value.trim(),recipientPhone:$('addrPhone').value.trim(),country:$('addrCountry').value,city:$('addrCity').value.trim(),district:$('addrDistrict').value.trim(),addressLine:$('addrLine').value.trim(),postalCode:$('addrPostal').value.trim(),notes:$('addrNotes').value.trim()};$('addressMsg').textContent='جارٍ الحفظ...';try{let r=await fetch('/api/participant/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:v.id,alias:v.alias||'',country:v.country||shippingAddress.country,avatarUrl:v.avatarUrl||'',shippingAddress})}),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر حفظ عنوان التسليم');v={...v,...d.participant};NawaderVisitor.set(v);applyProfile(v);$('addressMsg').textContent='✅ تم حفظ العنوان'+(d.activeOrdersUpdated?' وتحديث '+d.activeOrdersUpdated+' طلب نشط':'');await loadOrders(v)}catch(e){$('addressMsg').textContent='';alert(e.message)}};"""
    new_save="""if($('saveAddress'))$('saveAddress').onclick=async()=>{let v=NawaderVisitor.get();if(!v)return;let shippingAddress={recipientName:$('addrName').value.trim(),recipientPhone:$('addrPhone').value.trim(),country:$('addrCountry').value,city:$('addrCity').value.trim(),district:$('addrDistrict').value.trim(),addressLine:$('addrLine').value.trim(),postalCode:$('addrPostal').value.trim(),notes:$('addrNotes').value.trim()};let missing=[];if(!shippingAddress.country)missing.push('الدولة');if(!shippingAddress.city)missing.push('المدينة');if(!shippingAddress.addressLine)missing.push('العنوان بالتفصيل');if(missing.length){$('addressMsg').textContent='';alert('أكمل الحقول المطلوبة: '+missing.join('، '));window.focusShippingAddress?.(false);return}$('addressMsg').textContent='جارٍ الحفظ...';try{let r=await fetch('/api/participant/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:v.id,alias:v.alias||'',country:v.country||shippingAddress.country,avatarUrl:v.avatarUrl||'',shippingAddress})}),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر حفظ عنوان التسليم');v={...v,...d.participant};NawaderVisitor.set(v);applyProfile(v);$('shippingPanel')?.classList.remove('address-required');$('addressMsg').className='address-ok';$('addressMsg').textContent='✅ تم حفظ العنوان وتفعيله'+(d.activeOrdersUpdated?' على '+d.activeOrdersUpdated+' طلب نشط':'');try{history.replaceState(null,'',location.pathname)}catch(_){}await loadOrders(v)}catch(e){$('addressMsg').textContent='';alert(e.message)}};"""
    if old_save not in a:
        raise RuntimeError('saveAddress handler not found')
    a=a.replace(old_save,new_save,1)
    account.write_text(a,encoding='utf-8')

print('patched shipping address activation v1')
